image: python:3.12

pipelines:
  default:
    - step:
        name: Lint and format
        script:
          - pip install ruff
          - ruff format --diff  
          - ruff check . --select N
  custom:
    econ-upload:
      - step:
          runs-on:
            - self.hosted
            - windows
          name: "Migrate Econ Folder"
          script:
            - python svnExternals.py --migrate-econ-folder --local-path C:\econwTest
      - step:
          runs-on:
            - self.hosted
            - windows
          name: "Upload Econ Folder"
          script:
            - python svnExternals.py --upload-econ-folder --local-path C:\econwTest
    enablex1-upload:
      - step:
          runs-on:
            - self.hosted
            - windows
          name: "Migrate enableX1"
          script:
            - python svnExternals.py --remote-url http://ag-reposerver/repo/Projects/enAbleX1/SW/eX1 --migrate
      - step:
          runs-on:
            - self.hosted
            - windows
          name: "Upload enableX1"
          script:
            - python svnExternals.py --remote-url http://ag-reposerver/repo/Projects/enAbleX1/SW/eX1 --upload-no-externals
