image: python:3.12

pipelines:
  default:
    - parallel:
      - step:
          name: Install packages from requirements.txt
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - step:
          name: Lint and format
          script:
            - pip install ruff
            - ruff format --diff  
            - ruff check . --select N
