image: python:3.12

pipelines:
  default:
    - step:
        name: Lint and format
        script:
          - pip install ruff
          - ruff format --diff  
          - ruff check . --select N
  custom:
    econ-upload:
      - step:
          runs-on:
            - self.hosted
            - windows
          name: "Migrate Econ Folder"
          script:
            - python svnExternals.py --migrate-econ-folder --local-path C:\econwTest
      - step:
          runs-on:
            - self.hosted
            - windows
          name: "Upload Econ Folder"
          script:
            - python svnExternals.py --upload-econ-folder --local-path C:\econwTest
      - step:
          runs-on:
            - self.hosted
            - windows
          name: "Upload Econ subfolders"
          script:
            - python svnExternals.py --upload-econ-folder-subfolders --local-path C:\econwTest
      - step:
          runs-on:
            - self.hosted
            - windows
          name: "Upload Core with submodules"
          script:
            - python svnExternals.py --local-path C:\gitCheckoutTestCore --remote-url "http://ag-reposerver/repo/Projects/ECON/SW/Core" --checkout-git
    enablex1-upload:
      - step:
          runs-on:
            - self.hosted
            - windows
          name: "Migrate enableX1"
          script:
            - python svnExternals.py --remote-url http://ag-reposerver/repo/Projects/enAbleX1/SW/eX1 --migrate
      - step:
          runs-on:
            - self.hosted
            - windows
          name: "Upload enableX1"
          script:
            - python svnExternals.py --remote-url http://ag-reposerver/repo/Projects/enAbleX1/SW/eX1 --upload-no-externals
      - step:
          runs-on:
            - self.hosted
            - windows
          name: "Upload enableX1 subfolders"
          script:
            - python svnExternals.py --remote-url http://ag-reposerver/repo/Projects/enAbleX1/SW/eX1 --upload-no-externals-subfolders
      - step:
          runs-on:
            - self.hosted
            - windows
          name: "Upload enableX1 with submodules"
          script:
            - python svnExternals.py --local-path C:\gitCheckoutTestEnableX --remote-url "http://ag-reposerver/repo/Projects/enAbleX1/SW/eX1" --checkout-git
