image: python:3.12

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - step:
          name: Lint code
          script:
            - pip install ruff
            - ruff --select=ALL .
